### ISSUE TITLE
Replace microns with pixels, or add microns per pixel as a user inputted variable 

### ISSUE THREAD

**Issue by kylemxm** [GreggHeller1/dendritic_distance#1]
Microns per pixel is currently a fixed value (0.09) in the default config file. The value is outdated, as it comes from the pre-calibrated scope, and only ever applied to the 25x objective with 16x digital zoom anyway. I would suggest having the default output measurements be in pixels/square pixels, as this is applicable to everyone regardless of settings and they can rescale based on their own metadata later without recalculating or reinterpreting the output of dendritic-distance. In addition, you could add microns per pixel as an optional, user provided value.

**Comment by GreggHeller1** [comment]
That was the intent of having it in the config file - that users should make sure that the values in the config are are appropriate. They will have to edit file paths in their copy of this file either way. 

But I agree that the default should not be 0.09, this could be misleading and difficult to reverse. I will set the default value to 1

**Comment by kylemxm** [comment]
Default of 1 works. If the functions becomes general use, I would worry about users copying the config between experiments, just updating the paths and not scrolling down to notice the scaling factor.
